filebeat.inputs:
- type: mqtt
  hosts: 
    - 'tcp://127.0.0.1:1883'
  topics: 
    - dispositivos/#
  qos: 2
  client_id: filebeat_mqtt
  enabled: true
  fields_under_root: true
  index: 'sensor-data-%{+yyyy-MM-dd}'
output.elasticsearch:
  hosts: ["https://192.168.22.11:9200"]
  username: "elastic"
  password: "#PASSWORD#" 
  allow_older_versions: true
  ssl:
    verification_mode: none
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0640