filebeat.inputs:
- type: mqtt
  hosts: 
    - 'tcp://127.0.0.1:1883'
  topics: 
    - dispositivos/#
  qos: 2
  client_id: filebeat_mqtt
output.logstash:
  hosts: ["192.168.22.13:5044"]
  ttl: 120
  pipelining: 0
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0640