apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyT0RVeE16Y3hOalF3SGhjTk1qTXdOVEkyTWpFek9USTBXaGNOTXpNd05USXpNakV6T1RJMApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyT0RVeE16Y3hOalF3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUa1k3RWdEeGJENXRWZEx5WDc1OGdHckpGb20wUlFqamxUb0ljemkxNk4KZjl0ZVpFMkRCZHEweEZVM2JhS3FnRTNoQndiVlJPdVBzbGhmZGZEd2RabHZvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVThGY1ZPUjBibzZhemx4K3VpQ0dTCnBHc01jb0F3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnZkhSVS85NHFBNjNjaVZGb3NZOTFaKzZ2c0QwNUIyamUKcXkwYlUrQjdhc1FDSVFEaTdoYU96d3JTVUExTDF2ZkZCK0hzUk55cVprZDJTbllzSUdMR25zNzQwQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://127.0.0.1:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: admin-user
  user:
    username: admin-user